In [6]:
import numpy as np
import pandas as pd
from numpy import random
import os
os.getcwd()     #get current working directory
os.chdir("/content/drive/MyDrive")
os.getcwd
df=pd.read_excel('CDAC_DataBook (1).xlsx',sheet_name='ERPData')
df.head()       #by default 5 rows ahe shown
import scipy
from scipy import stats
from scipy.stats import norm,t
from collections import Counter
from scipy.stats import binom
from scipy.stats import poisson
from scipy.stats import expon



import seaborn as sns
import matplotlib
import matplotlib.pyplot as plt
import pylab
from pylab import legend
from pylab import plot,show,title,xlabel,ylabel


import statsmodels
from statsmodels import stats
from statsmodels.stats import weightstats as ssw

# **paired t test**

This test is used when we have two paired sample the. average differance between paired value is compared against claim value to esatablish wheather the differance is statistically significant.

the keyword here is before-after

In [9]:
before=np.array([12,14,10,9,8,13])

In [10]:
after=np.array([11.8,9.7,11.3,8.2,7.2,12.3])

In [ ]:
#H0 avg(before-after)>=2
#Ha avg(before-after)<2  ====>>>left tail test

In [11]:
d = (before - after)

In [12]:
d

array([ 0.2,  4.3, -1.3,  0.8,  0.8,  0.7])

In [13]:
np.mean(d)

np.float64(0.9166666666666665)

In [14]:
ssw.ttost_paired(before,after,low=2,upp=2)        #in ouput first 3 are right tail test and last 3 are left tail test. and 5 is defree if freedom

(np.float64(0.8954696830206994),
 (np.float64(-1.4413160909218492),
  np.float64(0.8954696830206994),
  np.float64(5.0)),
 (np.float64(-1.4413160909218492),
  np.float64(0.10453031697930062),
  np.float64(5.0)))

In [16]:
scipy.stats.ttest_1samp(before - after,popmean=2, alternative='less')

TtestResult(statistic=np.float64(-1.4413160909218492), pvalue=np.float64(0.10453031697930062), df=np.int64(5))

In [17]:
(np.mean(d) -2)/((np.std(d,ddof=1)/6**0.5))

np.float64(-1.4413160909218492)

In [18]:
t.cdf(-1.441316090921,5)

np.float64(0.1045303169794143)

# **4. One Way ANOVA.  ===> ANalysis Of VAariance**

This test is used when we have multiple sample. (more than 2)

This test will compared all the paired of the mean and check wheather they can be consider is equal or not

NULL hypothesis all the paired of means are equal

In [8]:
import statsmodels.api as sm
from statsmodels.formula.api import ols
import statsmodels.stats.multicomp

In [21]:
dfA = pd.DataFrame({'Col1':np.repeat('A',7),'Col2':np.random.randint(10,30,7)})
dfB = pd.DataFrame({'Col1':np.repeat('B',9),'Col2':np.random.randint(20,40,9)})
dfC = pd.DataFrame({'Col1':np.repeat('C',8),'Col2':np.random.randint(15,30,8)})
df = pd.concat([dfA,dfB,dfC])

In [22]:
df

  Col1  Col2
0    A    14
1    A    25
2    A    25
3    A    11
4    A    12
5    A    18
6    A    10
0    B    36
1    B    38
2    B    32
3    B    30
4    B    28
5    B    27
6    B    25
7    B    34
8    B    31
0    C    26
1    C    22
2    C    15
3    C    21
4    C    23
5    C    24
6    C    15
7    C    24

In [24]:
mod1=ols('Col2 ~ Col1',df).fit()      #ols = ordinary list square

In [25]:
tb1=sm.stats.anova_lm(mod1)

In [27]:
tb1

            df      sum_sq     mean_sq          F    PR(>F)
Col1       2.0  927.063492  463.531746  19.057834  0.000019
Residual  21.0  510.769841   24.322373        NaN       NaN

In [32]:
from statsmodels.stats.multicomp import pairwise_tukeyhsd
print(pairwise_tukeyhsd(df.Col2, df.Col1))

 Multiple Comparison of Means - Tukey HSD, FWER=0.05
=====================================================
group1 group2 meandiff p-adj   lower    upper  reject
-----------------------------------------------------
     A      B  14.7937    0.0   8.5291 21.0582   True
     A      C   4.8214 0.1666  -1.6122  11.255  False
     B      C  -9.9722 0.0012 -16.0125 -3.9319   True
-----------------------------------------------------

In [ ]:
df.to_excel('data_anova.xlsx')

In [18]:
cv=50

In [19]:
#H0 s>=50 Ha s<50

In [15]:
avg1=49.3

In [11]:
avg2=46.3

In [12]:
sd=1.5

In [13]:
n=50

In [20]:
z1=(avg1-cv)/(sd/n**0.5)

In [25]:
z2=(avg2-cv)/(sd/n**0.5)

In [26]:
z1

-3.2998316455372354

In [27]:
z2

-17.441967269268186

In [29]:
df=pd.read_excel('data_anova.xlsx')
df

   Col1  Col2
0     A    10
1     A    23
2     A    14
3     A    25
4     A    22
5     A    11
6     A    12
7     B    26
8     B    39
9     B    29
10    B    39
11    B    31
12    B    32
13    B    38
14    B    22
15    B    25
16    C    21
17    C    23
18    C    26
19    C    19
20    C    29
21    C    27
22    C    17
23    C    24

In [32]:
grp1=df.groupby('Col1')

In [33]:
grp1.agg('mean')

           Col2
Col1
A     16.714286
B     31.222222
C     23.250000

In [34]:
gm=np.mean(df.Col2)

In [39]:
gm

np.float64(24.333333333333332)

In [35]:
sm=grp1.agg('mean')

In [36]:
sm.loc['A']

Col2    16.714286
Name: A, dtype: float64

In [40]:
7*(sm.loc['A'] - gm)**2 + 9*(sm.loc['B'] - gm)**2 + 8*(sm.loc['C'] - gm)**2

Col2    842.849206
dtype: float64

diff. script

In [49]:
df = pd.read_excel('data_anova.xlsx')

In [50]:
df.index = np.arange(df.shape[0])

In [51]:
grp1 = df.groupby('Col1')

In [52]:
samp_mean = grp1.agg('mean')
samp_mean

           Col2
Col1
A     16.714286
B     31.222222
C     23.250000

In [53]:
grand_mean = np.mean(df.Col2)

In [54]:
#variation between
7*(samp_mean.loc['A'] - grand_mean)**2 + 9*(samp_mean.loc['B'] - grand_mean)**2 + 8*(samp_mean.loc['C'] - grand_mean)**2

Col2    842.849206
dtype: float64

In [55]:
sampA = df.Col2[np.where(df.Col1=='A')[0]]
sampB = df.Col2[np.where(df.Col1=='B')[0]]
sampC = df.Col2[np.where(df.Col1=='C')[0]]

In [56]:
#within sample
sum((np.array(sampA) - np.array(samp_mean.loc['A']))**2) +
sum((np.array(sampB) - np.array(samp_mean.loc['B']))**2) +
sum((np.array(sampC) - np.array(samp_mean.loc['C']))**2)

np.float64(684.484126984127)

In [61]:
684.484126984127 + 842.849206                 # total=within+between

1527.333332984127

In [62]:
sum((np.array(df.Col2) - np.array(grand_mean))**2)

np.float64(1527.3333333333333)

In [70]:
from statsmodels.formula.api import ols

mod1 = ols('Col2 ~ Col1',df).fit()

In [75]:
sample_means = grp1.agg('mean')

import statsmodels.api as sm
tbl = sm.stats.anova_lm(mod1)

In [76]:
print(tbl)

            df      sum_sq     mean_sq          F    PR(>F)
Col1       2.0  842.849206  421.424603  12.929323  0.000219
Residual  21.0  684.484127   32.594482        NaN       NaN

In [77]:
zoo = [34,43,57,40,85,68,67,53,41,24,42,52]
supp=[1,1,1,1,2,2,2,2,3,3,3,3]
lake=["R","D","R","D","R","D","R","D","R","D","R","D"]
df=pd.DataFrame({'Resp':zoo,"Factor1":supp,"Factor2":lake})

In [78]:
df.head()

   Resp  Factor1 Factor2
0    34        1       R
1    43        1       D
2    57        1       R
3    40        1       D
4    85        2       R

In [79]:
model=ols('Resp~Factor1+Factor2',df).fit()