In [102]:

import numpy as np
import pandas as pd
from numpy import random
import os
os.getcwd()     #get current working directory
os.chdir("/content/drive/MyDrive")
os.getcwd
df=pd.read_excel('CDAC_DataBook (1).xlsx',sheet_name='ERPData')
df.head()       #by default 5 rows ahe shown
import scipy
from scipy import stats
from scipy.stats import norm,t
from collections import Counter
from scipy.stats import binom
from scipy.stats import poisson
from scipy.stats import expon



import seaborn as sns
import matplotlib
import matplotlib.pyplot as plt
import pylab
from pylab import legend
from pylab import plot,show,title,xlabel,ylabel


import statsmodels
from statsmodels import stats
from statsmodels.stats import weightstats as ssw

import statsmodels.api as sm
from statsmodels.formula.api import ols
import statsmodels.stats.multicomp


import statsmodels.stats
from statsmodels.stats.proportion import proportions_ztest

from statsmodels.stats.rates import test_poisson_2indep

from scipy.stats import chi2

from scipy.stats import f

import sklearn

from sklearn.linear_model import LinearRegression

from sklearn.model_selection import cross_val_score

from sklearn.metrics import mean_squared_error

from sklearn.model_selection import train_test_split

import statsmodels.api as sm
from statsmodels.formula.api import ols
import statsmodels.stats.multicomp

from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import MinMaxScaler
from sklearn.preprocessing import RobustScaler
from statsmodels.stats.outliers_influence import variance_inflation_factor
from sklearn.metrics import log_loss

from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix

from sklearn.metrics import roc_auc_score
from statsmodels.discrete.discrete_model import MNLogit
from statsmodels.miscmodels.ordinal_model import OrderedModel
from sklearn.tree import DecisionTreeClassifier

In [103]:
df=pd.read_csv("Titanic.csv")

In [104]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [105]:
#servived is  response

In [106]:
df=df.drop(['PassengerId','Name','Ticket','Cabin'],axis=1)

In [107]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 8 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Survived  891 non-null    int64
 1   Pclass    891 non-null    int64
 2   Sex       891 non-null    object
 3   Age       714 non-null    float64
 4   SibSp     891 non-null    int64
 5   Parch     891 non-null    int64
 6   Fare      891 non-null    float64
 7   Embarked  889 non-null    object
dtypes: float64(2), int64(4), object(2)
memory usage: 55.8+ KB

In [108]:
df.Age=df.Age.fillna(df.Age.median())

In [109]:
df.Embarked.mode()

0    S
Name: Embarked, dtype: object

In [111]:
df.Emarked=df.Embarked.fillna('S')

In [112]:
df['NumPass']=df.SibSp +df.Parch

In [113]:
df

     Survived  Pclass     Sex   Age  SibSp  Parch     Fare Embarked  NumPass
0           0       3    male  22.0      1      0   7.2500        S        1
1           1       1  female  38.0      1      0  71.2833        C        1
2           1       3  female  26.0      0      0   7.9250        S        0
3           1       1  female  35.0      1      0  53.1000        S        1
4           0       3    male  35.0      0      0   8.0500        S        0
..        ...     ...     ...   ...    ...    ...      ...      ...      ...
886         0       2    male  27.0      0      0  13.0000        S        0
887         1       1  female  19.0      0      0  30.0000        S        0
888         0       3  female  28.0      1      2  23.4500        S        3
889         1       1    male  26.0      0      0  30.0000        C        0
890         0       3    male  32.0      0      0   7.7500        Q        0

[891 rows x 9 columns]

In [114]:
df=df.drop(['SibSp','Parch'],axis=1)

In [115]:
df

     Survived  Pclass     Sex   Age     Fare Embarked  NumPass
0           0       3    male  22.0   7.2500        S        1
1           1       1  female  38.0  71.2833        C        1
2           1       3  female  26.0   7.9250        S        0
3           1       1  female  35.0  53.1000        S        1
4           0       3    male  35.0   8.0500        S        0
..        ...     ...     ...   ...      ...      ...      ...
886         0       2    male  27.0  13.0000        S        0
887         1       1  female  19.0  30.0000        S        0
888         0       3  female  28.0  23.4500        S        3
889         1       1    male  26.0  30.0000        C        0
890         0       3    male  32.0   7.7500        Q        0

[891 rows x 7 columns]

In [116]:
#created dummy column for categorical data
dum_Pclass = pd.get_dummies(df.Pclass,drop_first=True,prefix='Pclass').astype(int)
dum_sex = pd.get_dummies(df.Sex,drop_first=True,prefix='Gender').astype(int)
dum_embarked = pd.get_dummies(df.Embarked,drop_first=True,prefix='Embark').astype(int)

In [117]:
dum_Pclass

     Pclass_2  Pclass_3
0           0         1
1           0         0
2           0         1
3           0         0
4           0         1
..        ...       ...
886         1         0
887         0         0
888         0         1
889         0         0
890         0         1

[891 rows x 2 columns]

In [118]:
dum_sex

     Gender_male
0              1
1              0
2              0
3              0
4              1
..           ...
886            1
887            0
888            0
889            1
890            1

[891 rows x 1 columns]

In [119]:
dum_embarked

     Embark_Q  Embark_S
0           0         1
1           0         0
2           0         1
3           0         1
4           0         1
..        ...       ...
886         0         1
887         0         1
888         0         1
889         0         0
890         1         0

[891 rows x 2 columns]

In [120]:
df = df.drop(['Pclass','Sex','Embarked'],axis=1)
df = pd.concat([df,dum_Pclass,dum_sex,dum_embarked], axis=1)

In [121]:
df.head()

,Survived,Age,Fare,NumPass,Pclass_2,Pclass_3,Gender_male,Embark_Q,Embark_S
0,0,22.0,7.2500,1,0,1,1,0,1
1,1,38.0,71.2833,1,0,0,0,0,0
2,1,26.0,7.9250,0,0,1,0,0,1
3,1,35.0,53.1000,1,0,0,0,0,1
4,0,35.0,8.0500,0,0,1,1,0,1

In [122]:
x=df.drop('Survived',axis=1)
y=df.Survived

In [123]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=20)

In [124]:
from sklearn.tree import DecisionTreeClassifier

In [125]:
dtc = DecisionTreeClassifier()

dtc.fit(x_train,y_train)

DecisionTreeClassifier()

In [126]:
#picking up noise
dtc.score(x_train,y_train)       # %age accuracy on training set

0.9845505617977528

In [127]:
dtc.score(x_test,y_test)

0.7988826815642458

In [128]:
#when we provide hyper parameter
#max_depth=3 is a parameter in a Decision Tree that limits how deep the tree can grow.
dtc = DecisionTreeClassifier(max_depth=3)

dtc.fit(x_train,y_train)

DecisionTreeClassifier(max_depth=3)

In [129]:
#dont picking up noise
dtc.score(x_train,y_train)

0.8258426966292135

In [130]:
dtc.score(x_test,y_test)

0.8156424581005587

In [131]:
y_pred=dtc.predict(x_test)

In [132]:
print(confusion_matrix(y_test,y_pred))

[[107   5]
 [ 28  39]]

In [133]:
146/(146+33)

0.8156424581005587

In [134]:
#hyper parameter

In [135]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=20)

**when response is categorical data**

In [136]:
from sklearn.tree import DecisionTreeClassifier     #when response is categorical data

In [137]:

# define instance for DecisionTreeClassifier WITHOUT hyperparameters
dtc = DecisionTreeClassifier()

In [138]:
# the big gap between training and test accuracy suggests overfitting

# to remove overfitting, hyper parameter values need to be set
# to get the best values for the the hyperparameters we do the Grid Search CV

param = {'max_depth':[2,3,4,5,6,7,8],
         'splitter':['best','random'],
         'criterion':['gini','entropy'],
         'min_samples_leaf':[2,3,4,5,6]}

from sklearn.model_selection import GridSearchCV

mod1 = GridSearchCV(dtc,param_grid=param,cv=5,scoring='accuracy')
mod1.fit(x_train,y_train)

GridSearchCV(cv=5, estimator=DecisionTreeClassifier(),
             param_grid={'criterion': ['gini', 'entropy'],
                         'max_depth': [2, 3, 4, 5, 6, 7, 8],
                         'min_samples_leaf': [2, 3, 4, 5, 6],
                         'splitter': ['best', 'random']},
             scoring='accuracy')

In [139]:
mod1.best_params_

{'criterion': 'gini',
 'max_depth': 7,
 'min_samples_leaf': 6,
 'splitter': 'best'}

In [140]:
# the above command gives the most appropriate values for the different hyperparameters

# define the instance dtc WITH hyperparameters
dtc = DecisionTreeClassifier(criterion='gini',
 max_depth=7,
 min_samples_leaf=6,
 splitter='best')

In [141]:
dtc.fit(x_train,y_train)
dtc.score(x_train,y_train)   # %age accuracy on training set

0.8707865168539326

In [142]:
dtc.score(x_test,y_test)

0.8435754189944135

In [143]:
y_pred = dtc.predict(x_test)

print(confusion_matrix(y_test,y_pred))

[[105   7]
 [ 21  46]]

**when response is contineous data**

In [144]:
from sklearn.tree import DecisionTreeRegressor

In [145]:
df = pd.read_excel('SalesData.xlsx')
dum_Region = pd.get_dummies(df.Region,drop_first=True,prefix='Reg').astype(int)
df = df.drop('Region', axis=1)
df = pd.concat([df,dum_Region], axis=1)

x = df.drop('Sales', axis=1)
y = df.Sales

x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=20)

from sklearn.tree import DecisionTreeRegressor

# define instance for DecisionTreeClassifier WITHOUT hyperparameters
dtr = DecisionTreeRegressor()
dtr.fit(x_train,y_train)

DecisionTreeRegressor()

In [146]:
dtr.score(x_train,y_train)    #gives the R2 values for the training set

1.0

In [147]:
dtr.score(x_test,y_test)      #gives the R2 value for the test set      # same as r_score

0.8548499445683468

In [148]:
from sklearn.metrics import r2_score

In [149]:
y_pred=dtr.predict(x_test)

In [150]:
r2_score(y_test,y_pred)   #its noting but the r2 its also give the same value .. its another way to calculate r2

0.8548499445683468

In [151]:
#hyperparam

In [162]:
params = {'max_depth':[3,4,5,6,7],
          'min_samples_split':[2,3,4,5],
          'min_samples_leaf':[2,3,4,5]}

In [163]:
mod1 = GridSearchCV(dtr,param_grid=params,cv=5,scoring='accuracy')

In [164]:
mod1.fit(x_train, y_train)
mod1.best_params_

{'max_depth': 3, 'min_samples_leaf': 2, 'min_samples_split': 2}

In [165]:
import warnings
warnings.filterwarnings('ignore')

In [167]:
dtr = DecisionTreeRegressor(max_depth=3,min_samples_leaf=2, min_samples_split=2)
dtr.fit(x_train,y_train)

DecisionTreeRegressor(max_depth=3, min_samples_leaf=2)

In [168]:
dtr.score(x_train,y_train)    # Gives the R2 value for the training set

0.8368972794176226

In [169]:
dtr.score(x_test,y_test)  # Gives the R2 value for the test set

0.8058459798835956