In [2]:
import numpy as np
import pandas as pd
from numpy import random
import os
os.getcwd()     #get current working directory
os.chdir("/content/drive/MyDrive")
os.getcwd

import scipy
from scipy import stats
from scipy.stats import norm,t
from collections import Counter
from scipy.stats import binom
from scipy.stats import poisson




import seaborn as sns
import matplotlib
import matplotlib.pyplot as plt
import pylab
from pylab import legend
from pylab import plot,show,title,xlabel,ylabel

In [62]:
df=pd.read_excel('CDAC_DataBook (1).xlsx',sheet_name='faithful')
df.head()

   eruptions  waiting
0      3.600       79
1      1.800       54
2      3.333       74
3      2.283       62
4      4.533       85

In [6]:
erupt=df.eruptions

In [7]:
np.mean(erupt)

np.float64(3.4877830882352936)

In [12]:
xbar=np.mean(erupt)
xbar

np.float64(3.4877830882352936)

In [13]:
n=len(erupt)
n

272

In [14]:
sd=np.std(erupt,ddof=1)
sd

1.1413712511052077

In [ ]:
#1-sample z test/ 1 sample t test

# this test is used to compare the sample mean of the one sample

#Used to check whether the difference betweent the sample mean and claim value can be ignored or not.
#Used to check whether the difference betweent the sample mean and claim value is statistically significant or not

In [15]:
import statsmodels
from statsmodels import stats
from statsmodels.stats import weightstats as ssw

In [15]:
ssw.ztest(erupt,value=3.6,alternative='smaller')

(np.float64(-1.621495827018525), np.float64(0.052455672107759366))

In [16]:
ssw.ztest(erupt,value=3.7,alternative='smaller')    #imp      p value 0.001 is very small value

(np.float64(-3.06646147570652), np.float64(0.0010830435959524984))

In [17]:
z=(xbar-3.7)/(sd/n**0.5)

In [18]:
z

np.float64(-3.066461475706521)

In [34]:
z=(xbar-3.53)/(sd/n**3.487)

In [35]:
z

np.float64(-11413038.960967908)

In [32]:
from scipy.stats import norm

In [33]:
#now this work perfectly
norm.ppf(0.05)

np.float64(-1.6448536269514729)

In [36]:
z=(xbar-3.53)/(sd/n**0.5)

In [37]:
z

np.float64(-0.6100198729369253)

In [25]:
# p_value, (area happening side) what will be the area on left side
norm.cdf(z)

np.float64(0.2709243216144542)

In [26]:
ssw.ztest(erupt,value=3.53,alternative='smaller')    #imp

(np.float64(-0.6100198729369251), np.float64(0.27092432161445423))

In [ ]:
#claim : u will not exceed 3.37
#Ho u<=3.37
#Ho u>3.37

In [27]:
ssw.ztest(erupt,value=3.37,alternative='smaller')    #imp

(np.float64(1.7019251649638607), np.float64(0.9556153011567042))

In [28]:
norm.ppf(0.95)    # 95% fault tolaurance

np.float64(1.6448536269514722)

In [30]:
#what is the area of 1.7 on side
norm.cdf(1.7)

np.float64(0.955434537241457)

In [31]:
1-norm.cdf(1.7019) #the area on the right side

np.float64(0.044565462758543006)

In [43]:
z=(xbar-3.53)/(sd/n**0.5)

In [44]:
z

np.float64(-0.6100198729369253)

In [45]:
zc=norm.ppf(0.05)

In [ ]:
#z>zc ====> non reejction zone, so  ho is not rejected

In [46]:
zc

np.float64(-1.6448536269514729)

In [47]:
norm.cdf(z)   # p value is 0.0117 >0.05 ===> ho is not rejected

np.float64(0.2709243216144542)

In [53]:
xbar+1.645 * sd/n**0.5

np.float64(3.6876427620307806)

In [63]:
df.head()

   eruptions  waiting
0      3.600       79
1      1.800       54
2      3.333       74
3      2.283       62
4      4.533       85

In [64]:
np.mean(df.waiting)

np.float64(70.8970588235294)

In [77]:
# min waiting time in 75 min
#1. test stat
#2. p value
#3. 95% UB

In [67]:
wait=df.waiting

In [68]:
xbar=np.mean(wait)

In [69]:
n=len(wait)

In [70]:
sd=np.std(wait,ddof=1)

In [71]:
z=(xbar -75)/(sd/n**0.5)        # -4.97 ==> no reject
z

np.float64(-4.977386527579323)

In [72]:
norm.cdf(z)     # p value is < 0.05 ==> no rejected

np.float64(3.222427049500585e-07)

In [73]:
xbar + 1.645*sd/n**0.5      #current mean of 7089 can go upto 72.25

np.float64(72.25305924622042)

In [74]:
xbar

np.float64(70.8970588235294)

In [75]:
ssw.ztest(wait,value=75,alternative='smaller')

(np.float64(-4.9773865275793225), np.float64(3.222427049500608e-07))

In [76]:
ssw.ztest(wait,value = 75,alternative ='two-sided')

(np.float64(-4.9773865275793225), np.float64(6.444854099001216e-07))

In [ ]:
#2-sample t test
#this test is used to compare the different of means of the


#this is used when the differnance of avarages of two independent sample has to be compare a claim value and establish where there differance is statistically significant or not

In [ ]:
# travel in blore is atleast 15 min more than

In [27]:
df=pd.read_excel('CDAC_DataBook (1).xlsx',sheet_name='faithful')
df.head()

   eruptions  waiting
0      3.600       79
1      1.800       54
2      3.333       74
3      2.283       62
4      4.533       85

In [5]:
df1=df.iloc[20:60]

In [6]:
df2=df.iloc[120:170]

In [7]:
df1.shape

(40, 2)

In [9]:
erupt1=df1.eruptions

In [10]:
erupt2=df2.eruptions

In [11]:
np.mean(erupt1)

np.float64(3.44745)

In [12]:
np.mean(erupt2)

np.float64(3.4876399999999994)

In [ ]:
#mean of erupt2 is atleast 0.12 more than the mean of erupt1

In [ ]:
# H0: mean(erupt2) - mean(erupt1) >=0.12

In [ ]:
# Ha: mean(erupt2) - mean(erupt1) <0.12

In [22]:
ssw.ztest(erupt2, erupt1, value=0.12, alternative='smaller')      # H0 e2bar - e1bar >=0.12      Ha e2bar - e1bar <0.12

(np.float64(-0.3196536558502502), np.float64(0.3746154475542464))

In [23]:
nr=np.mean(erupt2) -np.mean(erupt1) -0.12

In [24]:
dr =((np.std(erupt1,ddof=1))**2/len(erupt1) + (np.std(erupt2,ddof=1))**2/len(erupt2))**0.5

In [25]:
nr/dr

np.float64(-0.31844451421709036)

In [32]:
df=pd.read_csv('6-Churn_ModellingDataSet.csv')
df.head()

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

In [34]:
# does age have any influence on you exiting or not

Age0=df.Age[np.where(df.Exited==0)[0]]
Age1=df.Age[np.where(df.Exited==1)[0]]

ssw.ztest(Age0,Age1,value=0, alternative='two-sided')

(np.float64(-29.76681499437077), np.float64(1.0508082506224645e-194))

In [ ]:
# alternavtive method to find the subset