In [14]:
import numpy as np
import pandas as pd
from numpy import random

In [15]:
import os

In [16]:
os.getcwd()     #get current working directory

'/content'

In [17]:
os.chdir("/content/drive/MyDrive")

In [18]:
os.getcwd

In [7]:

df=pd.read_excel('CDAC_DataBook (1).xlsx',sheet_name='ERPData')

In [7]:
df.head()       #by default 5 rows ahe shown

  MaterialID Location  Quantity
0    TMI-43T    MWH-4        34
1    AXCP-78    MWH-1        67
2    LXCV-21    MWH-2        27
3    AXCP-78    MWH-5        65
4    AXCP-78    MWH-4        36

In [8]:
x1=np.random.randint(10,80,50)

In [9]:
df['Value']=x1

In [10]:
df.head()

  MaterialID Location  Quantity  Value
0    TMI-43T    MWH-4        34     69
1    AXCP-78    MWH-1        67     76
2    LXCV-21    MWH-2        27     65
3    AXCP-78    MWH-5        65     49
4    AXCP-78    MWH-4        36     41

In [ ]:
#grouping will always  done on categorical data
#cumulative >>> add

In [11]:
grp1=df.groupby('MaterialID')

In [12]:
grp1.groups

{'AXCP-78': [1, 3, 4, 24, 25, 37, 38, 39, 46, 47, 48], 'DDBN-89': [22, 23, 26, 30, 40, 43, 45, 49], 'GCVB-79': [8, 15, 34, 35, 36], 'LXCV-21': [2, 27, 28, 29, 44], 'SDRT-67': [10, 11, 16, 17, 41, 42], 'TMI-43T': [0, 5, 6, 7, 9, 12, 13, 14, 18, 19, 20, 21, 31, 32, 33]}

In [13]:
df.iloc[[1,3,4,24,25,37,38,39,46,47,48]]

   MaterialID Location  Quantity  Value
1     AXCP-78    MWH-1        67     76
3     AXCP-78    MWH-5        65     49
4     AXCP-78    MWH-4        36     41
24    AXCP-78    MWH-1       152     45
25    AXCP-78    MWH-1       109     65
37    AXCP-78    MWH-5        65     51
38    AXCP-78    MWH-5        70     66
39    AXCP-78    MWH-1       145     59
46    AXCP-78    MWH-2        85     38
47    AXCP-78    MWH-3        29     47
48    AXCP-78    MWH-1        75     15

In [14]:
grp1.get_group('SDRT-67')

   MaterialID Location  Quantity  Value
10    SDRT-67    MWH-1        34     47
11    SDRT-67    MWH-4        58     19
16    SDRT-67    MWH-5        12     56
17    SDRT-67    MWH-5       102     30
41    SDRT-67    MWH-1        57     54
42    SDRT-67    MWH-2        31     44

In [15]:
grp1.Quantity.mean()

MaterialID
AXCP-78    81.636364
DDBN-89    47.875000
GCVB-79    36.400000
LXCV-21    48.600000
SDRT-67    49.000000
TMI-43T    59.000000
Name: Quantity, dtype: float64

In [16]:
grp1.Quantity.agg(np.mean)

/tmp/ipykernel_8368/719844975.py:1: FutureWarning: The provided callable <function mean at 0x7d2417921940> is currently using SeriesGroupBy.mean. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "mean" instead.
  grp1.Quantity.agg(np.mean)

MaterialID
AXCP-78    81.636364
DDBN-89    47.875000
GCVB-79    36.400000
LXCV-21    48.600000
SDRT-67    49.000000
TMI-43T    59.000000
Name: Quantity, dtype: float64

In [17]:
grp1.Quantity.agg(np.size)      #size >>> frequency

MaterialID
AXCP-78    11
DDBN-89     8
GCVB-79     5
LXCV-21     5
SDRT-67     6
TMI-43T    15
Name: Quantity, dtype: int64

In [18]:
grp1.Quantity.agg([np.size,np.sum,np.mean])

/tmp/ipykernel_8368/58817162.py:1: FutureWarning: The provided callable <function sum at 0x7d2417920860> is currently using SeriesGroupBy.sum. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "sum" instead.
  grp1.Quantity.agg([np.size,np.sum,np.mean])
/tmp/ipykernel_8368/58817162.py:1: FutureWarning: The provided callable <function mean at 0x7d2417921940> is currently using SeriesGroupBy.mean. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "mean" instead.
  grp1.Quantity.agg([np.size,np.sum,np.mean])

            size  sum       mean
MaterialID
AXCP-78       11  898  81.636364
DDBN-89        8  383  47.875000
GCVB-79        5  182  36.400000
LXCV-21        5  243  48.600000
SDRT-67        6  294  49.000000
TMI-43T       15  885  59.000000

In [19]:
s1=grp1.Quantity.agg(np.size)

In [20]:
d1=pd.DataFrame(s1)

In [21]:
d1

            Quantity
MaterialID
AXCP-78           11
DDBN-89            8
GCVB-79            5
LXCV-21            5
SDRT-67            6
TMI-43T           15

In [22]:
d1.loc['SDRT-67']

Quantity    6
Name: SDRT-67, dtype: int64

In [26]:
np.where(d1.index=='SDRT-67')     #getting index of SDRT-67

(array([4]),)

In [27]:
d1.iloc[np.where(d1.index=='SDRT-67')]      #getting value of SDRT-67

            Quantity
MaterialID
SDRT-67            6

In [28]:
d1.index.name

'MaterialID'

In [30]:
d2=grp1.Quantity.agg([np.size,np.sum,np.mean])
d2

/tmp/ipykernel_8368/1234971915.py:1: FutureWarning: The provided callable <function sum at 0x7d2417920860> is currently using SeriesGroupBy.sum. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "sum" instead.
  d2=grp1.Quantity.agg([np.size,np.sum,np.mean])
/tmp/ipykernel_8368/1234971915.py:1: FutureWarning: The provided callable <function mean at 0x7d2417921940> is currently using SeriesGroupBy.mean. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "mean" instead.
  d2=grp1.Quantity.agg([np.size,np.sum,np.mean])

            size  sum       mean
MaterialID
AXCP-78       11  898  81.636364
DDBN-89        8  383  47.875000
GCVB-79        5  182  36.400000
LXCV-21        5  243  48.600000
SDRT-67        6  294  49.000000
TMI-43T       15  885  59.000000

In [31]:
d2.loc['SDRT-67','sum']   #fetching the sum from d2 ...........#>>>>>>>>extracting values of specific row

np.int64(294)

In [32]:
d2.iloc[4,1]

np.int64(294)

In [34]:
df=pd.read_excel('CDAC_DataBook (1).xlsx',sheet_name='Health')

In [35]:
df

   Country       Disease  2019  2020  2021
0    India        Cancer    12    94    35
1       UK        Cancer    95    19    84
2       US        Cancer    98    19    53
3    Japan        Cancer    89    52    14
4    India         Covid    38    19    62
5       UK         Covid    69    73    35
6       US         Covid    87    97    35
7    Japan         Covid    14    12    90
8    India  Heart Attack    84    10    98
9       UK  Heart Attack    44    17    24
10      US  Heart Attack    34    40    54
11   Japan  Heart Attack    11    43    75

In [37]:
df1=df.melt(id_vars=['Country','Disease'],var_name = 'year',value_name='cases')     #.melt >> means making larger(broader) data structure to smaller

In [38]:
df1

   Country       Disease  year  cases
0    India        Cancer  2019     12
1       UK        Cancer  2019     95
2       US        Cancer  2019     98
3    Japan        Cancer  2019     89
4    India         Covid  2019     38
5       UK         Covid  2019     69
6       US         Covid  2019     87
7    Japan         Covid  2019     14
8    India  Heart Attack  2019     84
9       UK  Heart Attack  2019     44
10      US  Heart Attack  2019     34
11   Japan  Heart Attack  2019     11
12   India        Cancer  2020     94
13      UK        Cancer  2020     19
14      US        Cancer  2020     19
15   Japan        Cancer  2020     52
16   India         Covid  2020     19
17      UK         Covid  2020     73
18      US         Covid  2020     97
19   Japan         Covid  2020     12
20   India  Heart Attack  2020     10
21      UK  Heart Attack  2020     17
22      US  Heart Attack  2020     40
23   Japan  Heart Attack  2020     43
24   India        Cancer  2021     35
25      UK        Cancer  2021     84
26      US        Cancer  2021     53
27   Japan        Cancer  2021     14
28   India         Covid  2021     62
29      UK         Covid  2021     35
30      US         Covid  2021     35
31   Japan         Covid  2021     90
32   India  Heart Attack  2021     98
33      UK  Heart Attack  2021     24
34      US  Heart Attack  2021     54
35   Japan  Heart Attack  2021     75

In [39]:
df.shape

(12, 5)

In [40]:
df1.shape

(36, 4)

In [43]:
df1

   Country       Disease  year  cases
0    India        Cancer  2019     12
1       UK        Cancer  2019     95
2       US        Cancer  2019     98
3    Japan        Cancer  2019     89
4    India         Covid  2019     38
5       UK         Covid  2019     69
6       US         Covid  2019     87
7    Japan         Covid  2019     14
8    India  Heart Attack  2019     84
9       UK  Heart Attack  2019     44
10      US  Heart Attack  2019     34
11   Japan  Heart Attack  2019     11
12   India        Cancer  2020     94
13      UK        Cancer  2020     19
14      US        Cancer  2020     19
15   Japan        Cancer  2020     52
16   India         Covid  2020     19
17      UK         Covid  2020     73
18      US         Covid  2020     97
19   Japan         Covid  2020     12
20   India  Heart Attack  2020     10
21      UK  Heart Attack  2020     17
22      US  Heart Attack  2020     40
23   Japan  Heart Attack  2020     43
24   India        Cancer  2021     35
25      UK        Cancer  2021     84
26      US        Cancer  2021     53
27   Japan        Cancer  2021     14
28   India         Covid  2021     62
29      UK         Covid  2021     35
30      US         Covid  2021     35
31   Japan         Covid  2021     90
32   India  Heart Attack  2021     98
33      UK  Heart Attack  2021     24
34      US  Heart Attack  2021     54
35   Japan  Heart Attack  2021     75

In [45]:
df3=df1.pivot_table(values='cases',index=['Country','year'],columns='Disease')
df3

Disease       Cancer  Covid  Heart Attack
Country year
India   2019    12.0   38.0          84.0
        2020    94.0   19.0          10.0
        2021    35.0   62.0          98.0
Japan   2019    89.0   14.0          11.0
        2020    52.0   12.0          43.0
        2021    14.0   90.0          75.0
UK      2019    95.0   69.0          44.0
        2020    19.0   73.0          17.0
        2021    84.0   35.0          24.0
US      2019    98.0   87.0          34.0
        2020    19.0   97.0          40.0
        2021    53.0   35.0          54.0

In [46]:
df3.shape

(12, 3)

In [47]:
df3.index     #multi index column

MultiIndex([('India', 2019),
            ('India', 2020),
            ('India', 2021),
            ('Japan', 2019),
            ('Japan', 2020),
            ('Japan', 2021),
            (   'UK', 2019),
            (   'UK', 2020),
            (   'UK', 2021),
            (   'US', 2019),
            (   'US', 2020),
            (   'US', 2021)],
           names=['Country', 'year'])

In [49]:
df3.columns

Index(['Cancer', 'Covid', 'Heart Attack'], dtype='object', name='Disease')

In [50]:
df3=df1.pivot_table(values='cases',index=['Country','year'],columns='Disease').reset_index()
df3.head()

Disease Country  year  Cancer  Covid  Heart Attack
0         India  2019    12.0   38.0          84.0
1         India  2020    94.0   19.0          10.0
2         India  2021    35.0   62.0          98.0
3         Japan  2019    89.0   14.0          11.0
4         Japan  2020    52.0   12.0          43.0

In [51]:
#remove the disease label from the index .. use rename_Axis(column=None)
df3=df1.pivot_table(values='cases',index=['Country','year'],columns='Disease').reset_index().rename_axis(columns=None)
df3

   Country  year  Cancer  Covid  Heart Attack
0    India  2019    12.0   38.0          84.0
1    India  2020    94.0   19.0          10.0
2    India  2021    35.0   62.0          98.0
3    Japan  2019    89.0   14.0          11.0
4    Japan  2020    52.0   12.0          43.0
5    Japan  2021    14.0   90.0          75.0
6       UK  2019    95.0   69.0          44.0
7       UK  2020    19.0   73.0          17.0
8       UK  2021    84.0   35.0          24.0
9       US  2019    98.0   87.0          34.0
10      US  2020    19.0   97.0          40.0
11      US  2021    53.0   35.0          54.0

In [52]:
df=pd.read_excel('CDAC_DataBook (1).xlsx',sheet_name='ERPData')

In [53]:
df.head()

  MaterialID Location  Quantity
0    TMI-43T    MWH-4        34
1    AXCP-78    MWH-1        67
2    LXCV-21    MWH-2        27
3    AXCP-78    MWH-5        65
4    AXCP-78    MWH-4        36

In [54]:
df1=df.pivot_table(values='Quantity',index=['MaterialID'],columns='Location')

In [56]:
df1

Location         MWH-1  MWH-2  MWH-3      MWH-4       MWH-5
MaterialID
AXCP-78     109.600000   85.0   29.0  36.000000   66.666667
DDBN-89      43.333333   69.0   38.0  37.500000   71.000000
GCVB-79            NaN   39.0    NaN        NaN   26.000000
LXCV-21            NaN   27.0   42.0        NaN   58.000000
SDRT-67      45.500000   31.0    NaN  58.000000   57.000000
TMI-43T     120.000000   29.0   65.0  50.818182  112.000000

In [61]:
df1=df.pivot_table(values='Quantity',index=['MaterialID'],columns=['Location'],aggfunc='size')

In [62]:
df1

Location    MWH-1  MWH-2  MWH-3  MWH-4  MWH-5
MaterialID
AXCP-78       5.0    1.0    1.0    1.0    3.0
DDBN-89       3.0    1.0    1.0    2.0    1.0
GCVB-79       NaN    4.0    NaN    NaN    1.0
LXCV-21       NaN    1.0    1.0    NaN    3.0
SDRT-67       2.0    1.0    NaN    1.0    2.0
TMI-43T       1.0    1.0    1.0   11.0    1.0

In [63]:
df1=df.pivot_table(values='Quantity',index=['MaterialID'],columns=['Location'],aggfunc='mean')
df1

Location         MWH-1  MWH-2  MWH-3      MWH-4       MWH-5
MaterialID
AXCP-78     109.600000   85.0   29.0  36.000000   66.666667
DDBN-89      43.333333   69.0   38.0  37.500000   71.000000
GCVB-79            NaN   39.0    NaN        NaN   26.000000
LXCV-21            NaN   27.0   42.0        NaN   58.000000
SDRT-67      45.500000   31.0    NaN  58.000000   57.000000
TMI-43T     120.000000   29.0   65.0  50.818182  112.000000

In [64]:
df1=df.pivot_table(values='Quantity',index=['MaterialID'],columns=['Location'],aggfunc='sum')
df1

Location    MWH-1  MWH-2  MWH-3  MWH-4  MWH-5
MaterialID
AXCP-78     548.0   85.0   29.0   36.0  200.0
DDBN-89     130.0   69.0   38.0   75.0   71.0
GCVB-79       NaN  156.0    NaN    NaN   26.0
LXCV-21       NaN   27.0   42.0    NaN  174.0
SDRT-67      91.0   31.0    NaN   58.0  114.0
TMI-43T     120.0   29.0   65.0  559.0  112.0

In [65]:
df1=df.pivot_table(values='Quantity',index=['MaterialID','Location'],columns=['Location'],aggfunc='size')
df1

Location             MWH-1  MWH-2  MWH-3  MWH-4  MWH-5
MaterialID Location
AXCP-78    MWH-1       5.0    NaN    NaN    NaN    NaN
           MWH-2       NaN    1.0    NaN    NaN    NaN
           MWH-3       NaN    NaN    1.0    NaN    NaN
           MWH-4       NaN    NaN    NaN    1.0    NaN
           MWH-5       NaN    NaN    NaN    NaN    3.0
DDBN-89    MWH-1       3.0    NaN    NaN    NaN    NaN
           MWH-2       NaN    1.0    NaN    NaN    NaN
           MWH-3       NaN    NaN    1.0    NaN    NaN
           MWH-4       NaN    NaN    NaN    2.0    NaN
           MWH-5       NaN    NaN    NaN    NaN    1.0
GCVB-79    MWH-2       NaN    4.0    NaN    NaN    NaN
           MWH-5       NaN    NaN    NaN    NaN    1.0
LXCV-21    MWH-2       NaN    1.0    NaN    NaN    NaN
           MWH-3       NaN    NaN    1.0    NaN    NaN
           MWH-5       NaN    NaN    NaN    NaN    3.0
SDRT-67    MWH-1       2.0    NaN    NaN    NaN    NaN
           MWH-2       NaN    1.0    NaN    NaN    NaN
           MWH-4       NaN    NaN    NaN    1.0    NaN
           MWH-5       NaN    NaN    NaN    NaN    2.0
TMI-43T    MWH-1       1.0    NaN    NaN    NaN    NaN
           MWH-2       NaN    1.0    NaN    NaN    NaN
           MWH-3       NaN    NaN    1.0    NaN    NaN
           MWH-4       NaN    NaN    NaN   11.0    NaN
           MWH-5       NaN    NaN    NaN    NaN    1.0

In [66]:
df1.xs('MWH-1',level=1)

Location    MWH-1  MWH-2  MWH-3  MWH-4  MWH-5
MaterialID
AXCP-78       5.0    NaN    NaN    NaN    NaN
DDBN-89       3.0    NaN    NaN    NaN    NaN
SDRT-67       2.0    NaN    NaN    NaN    NaN
TMI-43T       1.0    NaN    NaN    NaN    NaN

Descreiptive statics

In [19]:
df=pd.read_excel('CDAC_DataBook (1).xlsx',sheet_name='ERPData')
df.head()

  MaterialID Location  Quantity
0    TMI-43T    MWH-4        34
1    AXCP-78    MWH-1        67
2    LXCV-21    MWH-2        27
3    AXCP-78    MWH-5        65
4    AXCP-78    MWH-4        36

In [8]:
x1=df.MaterialID

In [9]:
np.unique(x1)

array(['AXCP-78', 'DDBN-89', 'GCVB-79', 'LXCV-21', 'SDRT-67', 'TMI-43T'],
      dtype=object)

In [10]:
len(np.unique(x1))

6

In [11]:
np.unique(x1,return_counts=True)

(array(['AXCP-78', 'DDBN-89', 'GCVB-79', 'LXCV-21', 'SDRT-67', 'TMI-43T'],
       dtype=object),
 array([11,  8,  5,  5,  6, 15]))

In [12]:
x1.value_counts()

MaterialID
TMI-43T    15
AXCP-78    11
DDBN-89     8
SDRT-67     6
GCVB-79     5
LXCV-21     5
Name: count, dtype: int64

In [13]:
x1.value_counts().reset_index()

  MaterialID  count
0    TMI-43T     15
1    AXCP-78     11
2    DDBN-89      8
3    SDRT-67      6
4    GCVB-79      5
5    LXCV-21      5

In [14]:
df1=x1.value_counts().reset_index()

In [15]:
df1

  MaterialID  count
0    TMI-43T     15
1    AXCP-78     11
2    DDBN-89      8
3    SDRT-67      6
4    GCVB-79      5
5    LXCV-21      5

In [19]:
df1.sum()

MaterialID    TMI-43TAXCP-78DDBN-89SDRT-67GCVB-79LXCV-21
count                                                 50
dtype: object

In [27]:
df1['prop']=df1['count']/sum(df1['count'])      #proportion

df1

  MaterialID  count  prop
0    TMI-43T     15  0.30
1    AXCP-78     11  0.22
2    DDBN-89      8  0.16
3    SDRT-67      6  0.12
4    GCVB-79      5  0.10
5    LXCV-21      5  0.10

In [28]:
df1['pct']=df1['prop']*100        #proportion percentage
df1

  MaterialID  count  prop   pct
0    TMI-43T     15  0.30  30.0
1    AXCP-78     11  0.22  22.0
2    DDBN-89      8  0.16  16.0
3    SDRT-67      6  0.12  12.0
4    GCVB-79      5  0.10  10.0
5    LXCV-21      5  0.10  10.0

In [29]:
x2=np.array([4,7,5,2,3,8])

In [30]:
np.cumsum(x2)     #cumulative sum

array([ 4, 11, 16, 18, 21, 29])

In [31]:
#what percentage of consignment to do top 3  material id

df1['cumpct']=np.cumsum(df1['pct'])             #data summarization with categorical data
df1

  MaterialID  count  prop   pct  cumpct
0    TMI-43T     15  0.30  30.0    30.0
1    AXCP-78     11  0.22  22.0    52.0
2    DDBN-89      8  0.16  16.0    68.0
3    SDRT-67      6  0.12  12.0    80.0
4    GCVB-79      5  0.10  10.0    90.0
5    LXCV-21      5  0.10  10.0   100.0

central tendency -Mean,median and mode

dispersion or variation or speed - range,inter quartile range, variance and std deviation

shape - skewness and kuetosis

In [38]:
x1=np.array([3,4,5,6])

In [39]:
x2=np.array([20,18,9,12])

In [40]:
sum(x1*x2/sum(x2))              #weighted average

np.float64(4.220338983050848)

In [43]:
(800-8)/20+40

79.6

In [ ]:
sal1=
sal2=

In [ ]:
np.median(sal1)

In [ ]:
np.median(sal2)

mean should be used only when there are no extreme value in the data set

mean should be used only when data is symmetrically distributed

median can be used in all cases

mode only parameter calculated for quantitative data and it can have more than 1 value

bimode
trimode
multimode

## **DAY 6**

In [20]:
df=pd.read_excel('CDAC_DataBook (1).xlsx',sheet_name='faithful')

In [21]:
df.head()

   eruptions  waiting
0      3.600       79
1      1.800       54
2      3.333       74
3      2.283       62
4      4.533       85

In [22]:
x1=df.eruptions

In [23]:
len(x1)

272

In [24]:
sum(x1)/len(x1)

3.487783088235294

In [25]:
np.mean(x1)

np.float64(3.4877830882352936)

In [27]:
np.median(x1)

np.float64(4.0)

In [28]:
import scipy
from scipy import stats

In [15]:
stats.mode(x1)

ModeResult(mode=np.float64(1.867), count=np.int64(8))

In [29]:
len(np.where(x1==1.867)[0])

8

In [30]:
from collections import Counter

In [20]:
Counter(x1).most_common()

[(1.867, 8),
 (4.5, 8),
 (1.833, 7),
 (4.7, 6),
 (1.75, 6),
 (4.8, 6),
 (4.0, 6),
 (4.533, 5),
 (4.083, 5),
 (3.833, 5),
 (4.333, 5),
 (3.6, 4),
 (1.8, 4),
 (4.35, 4),
 (4.25, 4),
 (1.883, 4),
 (2.0, 4),
 (4.167, 4),
 (4.417, 4),
 (4.6, 4),
 (4.15, 4),
 (4.583, 4),
 (3.917, 3),
 (1.967, 3),
 (2.017, 3),
 (4.567, 3),
 (2.1, 3),
 (4.633, 3),
 (1.817, 3),
 (1.983, 3),
 (4.933, 3),
 (2.2, 3),
 (4.367, 3),
 (4.233, 3),
 (4.45, 3),
 (3.333, 2),
 (2.167, 2),
 (3.85, 2),
 (4.433, 2),
 (4.3, 2),
 (4.467, 2),
 (4.033, 2),
 (4.833, 2),
 (2.233, 2),
 (4.133, 2),
 (4.1, 2),
 (4.067, 2),
 (3.95, 2),
 (4.817, 2),
 (4.667, 2),
 (4.9, 2),
 (1.783, 2),
 (3.767, 2),
 (1.917, 2),
 (2.033, 2),
 (2.4, 2),
 (3.567, 2),
 (3.5, 2),
 (1.933, 2),
 (2.083, 2),
 (2.417, 2),
 (2.25, 2),
 (4.267, 2),
 (4.117, 2),
 (1.85, 2),
 (4.283, 2),
 (2.283, 1),
 (2.883, 1),
 (1.95, 1),
 (4.2, 1),
 (1.6, 1),
 (3.45, 1),
 (3.067, 1),
 (3.367, 1),
 (4.783, 1),
 (3.317, 1),
 (4.716, 1),
 (1.733, 1),
 (4.883, 1),
 (3.717, 1),
 (1.667, 1),
 (4.317, 1),
 (4.4, 1),
 (2.067, 1),
 (5.067, 1),
 (3.883, 1),
 (2.633, 1),
 (4.517, 1),
 (3.75, 1),
 (2.483, 1),
 (4.05, 1),
 (4.85, 1),
 (3.683, 1),
 (4.733, 1),
 (2.3, 1),
 (1.7, 1),
 (2.317, 1),
 (2.617, 1),
 (2.267, 1),
 (4.65, 1),
 (2.8, 1),
 (4.383, 1),
 (3.733, 1),
 (5.1, 1),
 (5.033, 1),
 (3.967, 1),
 (2.367, 1),
 (5.0, 1),
 (4.617, 1),
 (2.183, 1),
 (3.966, 1),
 (4.366, 1),
 (2.383, 1),
 (3.417, 1),
 (4.483, 1),
 (4.55, 1),
 (4.183, 1),
 (2.217, 1),
 (2.333, 1),
 (2.35, 1),
 (2.9, 1),
 (2.133, 1),
 (3.817, 1),
 (4.767, 1),
 (4.75, 1),
 (2.15, 1)]

In [31]:
#peak to peak(ptp)

max(x1) - min(x1)

3.4999999999999996

In [32]:
np.ptp(x1)

np.float64(3.4999999999999996)

In [35]:
IQR=np.percentile(x1,75) - np.percentile(x1,25)

In [36]:
IQR

np.float64(2.2915)

In [38]:
i=1+(23-1)*75/1000

In [39]:
i

2.65

In [40]:
x2=[4,3,6,5,7,9,4,8,7,3]

In [41]:
np.var(x2)

np.float64(4.04)

In [42]:
np.std(x2)        #population of std deviation

np.float64(2.009975124224178)

In [43]:
np.var(x2,ddof=1)

np.float64(4.488888888888889)

In [44]:
np.std(x2,ddof=1)     #sample std deviation         ddof==(degrees of freedom)

np.float64(2.1186998109427604)

chance of rain on any given ay in june in mumbai is 0.7

if i am in mumbai for 15 days what is the probabilit that

a.it rains for exactly 10 days

b. it rains for maximum 10 days

c.it rains for minimum 10 days

In [45]:
from scipy.stats import binom

In [46]:
binom.pmf(10,15,0.7)            #exact 10

np.float64(0.20613038097752098)

In [47]:
binom.cdf(10,15,0.7)        #0,1,2,3,4,5,6,7,8,9,10. <=10

np.float64(0.4845089407731571)

In [48]:
1-binom.cdf(10,15,0.7)

np.float64(0.5154910592268429)

In [49]:
1-binom.cdf(9,15,0.7)       #answer of c 10,11,12,13,14,15  >=10

np.float64(0.7216214402043639)

In [50]:
import scipy
from scipy import stats
from scipy.stats import binom

binom.sf(9,15,0.7)

np.float64(0.7216214402043639)

possion distribution

avg number of occurance is 15. what is the probability of

a.exactly 12 incident taking place today

In [51]:
from scipy.stats import poisson

In [52]:
poisson.pmf(12,15)

np.float64(0.08285923436864541)

b. upto 12 incident take place

In [53]:
poisson.cdf(12,5)

np.float64(0.997981148372563)

c.minimum 12 incident take place

In [54]:
1-poisson.cdf(11,15)

np.float64(0.8152482009760685)

In [55]:
poisson.sf(11,15)

np.float64(0.8152482009760685)

In [56]:
#continuos data have two option is

In [62]:
from scipy.stats import norm, t

In [64]:
norm.cdf(14,16,2.3)

np.float64(0.19226902649831168)

In [65]:
1-norm.cdf(14,16,2.3)

np.float64(0.8077309735016883)

In [66]:
norm.sf(14,16,2.3)

np.float64(0.8077309735016883)

In [68]:
norm.cdf(17,16,2.3) - norm.cdf(13,16,2.3)

np.float64(0.5720823773874264)

**z value**

cdf left

 sf right

In [72]:
norm.cdf(14,16,2.3)

np.float64(0.19226902649831168)

In [69]:
z=(14-16)/2.3

In [70]:
norm.cdf(z)

np.float64(0.19226902649831168)

In [71]:
norm.sf(z)

np.float64(0.8077309735016883)

In [73]:
z

-0.8695652173913044